name: C/C++ CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: mkdir rabbit_dependency; git clone https://github.com/alanxz/rabbitmq-c ; mkdir build && cd build; cmake .. ; 
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
