name: C/C++ CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: |
        sudo apt-get install -y librtlsdr-dev
        mkdir rabbit_dependency
        cd rabbit_dependency
        git clone https://github.com/alanxz/rabbitmq-c 
        cd rabbitmq-c
        mkdir build 
        cd build
        sudo cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
        sudo cmake --build . --target install
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
